package practice1011;

public class Task {
	
	
	int id;
	String name;
	public Task() {}
	
	/*
	 * This code defines two constructors for a Java class named 'Task'.
	 * Constructors are special methods used to initialize objects of a class.
	 */

	// Constructor 1: Initializes a Task object with only a 'name'.
	// This is typically used when creating a new Task where the 'id' might be
	// auto-generated by a database later.
	public Task(String name) {
		// Calls the constructor of the superclass (Object in this case).
		// This is implicitly called even if not explicitly written.
		super();
		// Assigns the provided 'name' argument to the 'name' field of the Task object.
		this.name = name;
	}

	// Constructor 2: Initializes a Task object with both an 'id' and a 'name'.
	// This is often used when retrieving a Task from a database, where both
	// the 'id' and 'name' are already known.
	public Task(int id, String name) {
		// Calls the constructor of the superclass.
		super();
		// Assigns the provided 'id' argument to the 'id' field of the Task object.
		this.id = id;
		// Assigns the provided 'name' argument to the 'name' field of the Task object.
		this.name = name;
	}

}
